mysql:
  hostname: mysql
  domainname: localdomain
  build: mysql
  command: /sbin/my_init
  environment:
    - MYSQL_PASS=secret

phpmyadmin:
  hostname: phpmyadmin
  domainname: localdomain
  build: phpmyadmin
  command: /sbin/my_init
  environment:
    - MYSQL_USER=root
    - MYSQL_PASS=secret
    - MYSQL_ADDR=mysql
    - MYSQL_PORT=3306
  links:
    - mysql:mysql

laravel:
  hostname: laravel
  domainname: localdomain
  build: laravel
  command: /sbin/my_init
  environment:
    - MYSQL_USER=root
    - MYSQL_PASS=secret
    - MYSQL_ADDR=mysql
    - MYSQL_PORT=3306
    - SDH_API_HOST=http://sdhapi:8080
    - LARAVEL_DB=homestead
  links:
    - mysql:mysql
  ports:
    - "9003:80"
